#Operaciones aritmeticas 
print("La suma de 10 + 4 es: ", 3 + 4)
print(10-4,10*4, 10/4, 10%4, 10//4)


#Ecuacion cuadratica
a,b,c = 2,-7,3
x1 = (-b + (b**2 -4*a*c)**(0.5))/(2*a)
x2 = (-b - (b**2 -4*a*c)**(0.5))/(2*a)
print("x1: ",x1)
print("x2: ",x2)

#cadenas con texto
print("SNPP " + "CTFPP " + "PROGRAMACION PYTHON ")
print("AULA" + "2102"),str(2102)

#Operaciones mixtas
print("Tun chi " * 5)
print("Ja " * (2**3))

#Opercaiones de comparacion
print(3 > 4)
print(3 < 4)
print(3 >= 4)
print(4 <= 4)
print(3 == 4)
print(3 != 4)

#Operciones con cadenas de texto
print("python" > "PYTHON")
print("aaaa" >= "abaa")
print(len("aaaa") >= len("abaa"))

print("python" != "PYTHON")

#Operaciones logicas 
print(10 > 4 and "Z" > "A")
print(10 > 4 or "Z" > "A")
print(10 >= 4 and "Z" > "A")

